version: '3'
services:
  porfolio_webserver:
    build:
      context: ./
      dockerfile: DevBox.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - porfolio_database:porfolio_database
    volumes:
      - ./src:/var/www/html/
  porfolio_database:
    build:
      context: ./
      dockerfile: MySQL.Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    restart: always
    volumes:
            - ./database:/var/lib/mysql
  porfolio_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'porfolio_phpmyadmin'
    links:
      - porfolio_database:porfolio_database
    environment:
      PMA_HOST: porfolio_database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    ports:
      - '8080:80'
    volumes:
      - ./sessions
  porfolio_mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '8025:8025'